=== iqb-berlin/item-table/data-specs/item-table-dataset.schema.json
{
  "$id": "item-table-dataset@vera-standard@1.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Item table dataset",
  "description": "Data structure to unite all data for a subject.",
  "type": "object",
  "properties": {
    "objectType": {
      "type": "string",
      "pattern": "^[A-Za-z_]+$",
      "description": "Identifier and version of the object spec",
      "examples": [
        "vera-item-table@1.0"
      ]
    },
    "subject": {
      "type": "string",
      "enum": [
        "V3MA",
        "V3DE",
        "V8MA",
        "V8DE",
        "V8EN",
        "V8FR"
      ],
      "description": "Refers to VERA-Projekt (VERA3 or VERA8) and to subject (mathematics, German, English, French)",
      "examples": [
        "V3MA",
        "V8DE"
      ]
    },
    "yearOfApplication": {
      "type": "integer"
    },
    "yearOfTryout": {
      "type": "integer"
    },
    "publisher": {
      "type": "string",
      "description": "Instituion responsible for the content.",
      "examples": [
        "IQB - Institut zur Qualit√§tsentwicklung im Bildungswesen"
      ]
    },
    "created": {
      "type": "string",
      "description": "Date and time of creating these data.",
      "examples": [
        "06.06.2024 17:32"
      ]
    },
    "tasks": {
      "type": "array",
      "description": "List of tasks",
      "items": {
        "$ref": "task.schema.json"
      }
    },
    "items": {
      "type": "array",
      "description": "List of items",
      "items": {
        "$ref": "item.schema.json"
      }
    },
    "modules": {
      "type": "array",
      "description": "List of modules",
      "items": {
        "$ref": "test-module.schema.json"
      }
    },
    "booklets": {
      "type": "array",
      "description": "List of booklets",
      "items": {
        "$ref": "booklet.schema.json"
      }
    },
    "vocabs": {
      "type": "array",
      "description": "List of vocabs",
      "items": {
        "$ref": "vocab.schema.json"
      }
    }
  },
  "required": [
    "objectType",
    "subject",
    "publisher",
    "tasks",
    "items",
    "modules",
    "booklets",
    "vocabs"
  ]
}

=== iqb-berlin/item-table/data/2023/V8FR-2023_item-table.json
{
  "objectType": "vera-item-table@1.0",
  "subject": "V8FR",
  "yearOfApplication": 2023,
  "yearOfTryout": 2022,
  "publisher": "IQB - Institut zur Qualitätsentwicklung im Bildungswesen",
  "created": "19.06.2024 15:45",
  "tasks": [
    {
      "id": "CO22047",
      "label": "Dans un grand magasin",
      "title": "Dans un grand magasin",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO1081",
      "label": "Quel temps fait-il",
      "title": "Quel temps fait-il ?",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22005",
      "label": "Les microplastiques",
      "title": "Les microplastiques",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO1047",
      "label": "Panique en maths",
      "title": "Panique en maths",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22061",
      "label": "Un Francais curieux",
      "title": "Un Français curieux",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO817",
      "label": "Annonce",
      "title": "Annonce ",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO871",
      "label": "Message de Sébastien ",
      "title": "Message de Sébastien ",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22076",
      "label": "A la cafeteria",
      "title": "A la cafétéria",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22010",
      "label": "La meteo en France",
      "title": "La météo en France",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22012",
      "label": "Ma famille et mes amis",
      "title": "Ma famille et mes amis",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO998",
      "label": "Club judo",
      "title": "Club judo",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO996",
      "label": "Un sejour a Montpellier",
      "title": "Un séjour à Montpellier",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22036",
      "label": "Le photographe",
      "title": "Le photographe",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22079",
      "label": "Au musee",
      "title": "Au musée",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22034",
      "label": "Au college",
      "title": "Au collège",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22040",
      "label": "Un message",
      "title": "Un message",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO843",
      "label": "Lennui a lecole",
      "title": "L'ennui à l'école",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO937",
      "label": "Faire les courses",
      "title": "Faire les courses",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22071",
      "label": "Fin de lechange",
      "title": "Fin de l’échange",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22031",
      "label": "Vacances en France",
      "title": "Vacances en France",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22028",
      "label": "Blob a Paris",
      "title": "Blob à Paris",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO944",
      "label": "Au commissariat",
      "title": "Au commissariat",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22050",
      "label": "Parkourons Dijon",
      "title": "Parkourons Dijon",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CO22081",
      "label": "Au musee",
      "title": "Au musée",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Hörverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2142",
      "label": "Ma maison",
      "title": "Ma maison",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2156",
      "label": "Une question de lumiere",
      "title": "Une question de lumière",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2138",
      "label": "Fete danniversaire",
      "title": "Fête d'anniversaire",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2141",
      "label": "Avant et apres",
      "title": "Avant et après",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2188",
      "label": "Un café à Paris",
      "title": "Un café à Paris",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE2170",
      "label": "Un livre",
      "title": "Un livre",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE1087",
      "label": "Ce qui rend heureux",
      "title": "Ce qui rend heureux",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
      "id": "CE21109",
      "label": "Le quart dheure charentais",
      "title": "Le quart d’heure charentais",
      "subject": "V8FR",
      "metadata": [
        {
          "key": "enfr_domain",
          "value": "Leseverstehen"
        }
      ],
      "yearOfTryout": 2022,
      "yearOfApplication": 2023
    },
    {
